class ProAI {
    constructor() {
        this.init();
    }

    init() {
        this.bindEvents();
    }

    bindEvents() {
        // App Generator
        document.getElementById('generateApp').addEventListener('click', () => this.generateApp());
        document.getElementById('runApp').addEventListener('click', () => this.runApp());
        document.getElementById('copyCode').addEventListener('click', () => this.copyCode());
        document.getElementById('downloadApp').addEventListener('click', () => this.downloadApp());

        // Problem Solver
        document.getElementById('solveProblem').addEventListener('click', () => this.solveProblem());

        // Smooth scrolling
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                document.querySelector(this.getAttribute('href')).scrollIntoView({
                    behavior: 'smooth'
                });
            });
        });
    }

    async generateApp() {
        const prompt = document.getElementById('appPrompt').value.trim();
        if (!prompt) {
            alert('Please describe your app!');
            return;
        }

        const btn = document.getElementById('generateApp');
        btn.disabled = true;
        btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Generating...';

        try {
            const appCode = await this.createAppFromPrompt(prompt);
            this.showAppPreview(appCode);
            document.getElementById('downloadApp').disabled = false;
        } catch (error) {
            console.error('Generation failed:', error);
            alert('App generation failed. Please try again.');
        } finally {
            btn.disabled = false;
            btn.innerHTML = '<i class="fas fa-rocket"></i> Generate App';
        }
    }

    async createAppFromPrompt(prompt) {
        // Simulate AI processing - In production, call real AI API
        return new Promise((resolve) => {
            setTimeout(() => {
                const app = AppGenerator.generate(prompt);
                resolve(app);
            }, 2000);
        });
    }

    showAppPreview(appCode) {
        const preview = document.getElementById('appPreview');
        const frame = document.getElementById('previewFrame');
        
        // Create HTML for preview
        const previewHTML = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Preview - ${appCode.name}</title>
                <style>${appCode.css}</style>
            </head>
            <body>
                ${appCode.html}
                <script>${appCode.js}</script>
                <div style="position:fixed;bottom:10px;right:10px;background:#667eea;color:white;padding:10px;border-radius:5px;font-size:12px;">
                    Pro AI Generated App
                </div>
            </body>
            </html>
        `;
        
        frame.srcdoc = previewHTML;
        preview.classList.remove('hidden');
        
        // Store generated code
        window.generatedApp = appCode;
    }

    runApp() {
        document.getElementById('previewFrame').focus();
    }

    copyCode() {
        const code = JSON.stringify(window.generatedApp, null, 2);
        navigator.clipboard.writeText(code).then(() => {
            alert('✅ Code copied to clipboard!');
        });
    }

    downloadApp() {
        if (!window.generatedApp) return;
        
        const zip = new JSZip();
        const folder = zip.folder('pro-ai-app');
        
        folder.file('index.html', window.generatedApp.html);
        folder.file('style.css', window.generatedApp.css);
        folder.file('script.js', window.generatedApp.js);
        folder.file('README.md', `# ${window.generatedApp.name}\n\nGenerated by Pro AI`);
        
        zip.generateAsync({type: 'blob'}).then((content) => {
            const link = document.createElement('a');
            link.href = URL.createObjectURL(content);
            link.download = `${window.generatedApp.name.replace(/\s+/g, '-').toLowerCase()}.zip`;
            link.click();
        });
    }

    async solveProblem() {
        const prompt = document.getElementById('problemPrompt').value.trim();
        if (!prompt) {
            alert('Please describe your problem!');
            return;
        }

        const btn = document.getElementById('solveProblem');
        btn.disabled = true;
        btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Solving...';

        try {
            const solution = await this.getSolution(prompt);
            document.getElementById('solutionOutput').innerHTML = `
                <h3>✅ Solution Found!</h3>
                <div style="background:#e8f5e8;padding:1.5rem;border-radius:10px;border-left:4px solid #28a745;">
                    <pre style="white-space:pre-wrap;margin:0;font-size:1rem;">${solution}</pre>
                </div>
            `;
        } catch (error) {
            document.getElementById('solutionOutput').innerHTML = `
                <div style="background:#f8d7da;padding:1.5rem;border-radius:10px;border-left:4px solid:#dc3545;color:#721c24;">
                    Sorry, I couldn't find a solution. Please try rephrasing your question.
                </div>
            `;
        } finally {
            btn.disabled = false;
            btn.innerHTML = '<i class="fas fa-solve"></i> Solve Now';
        }
    }

    async getSolution(prompt) {
        // Simulate AI solution - Replace with real AI API
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve(this.mockSolution(prompt));
            }, 1500);
        });
    }

    mockSolution(prompt) {
        // Smart mock responses based on common problems
        if (prompt.toLowerCase().includes('cors')) {
            return `🚀 **CORS Error Fix:**

1. **Backend**: Add CORS headers
\`\`\`javascript
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  next();
});
\`\`\`

2. **Proxy (Development)**: Add to package.json
\`\`\`json
"proxy": "http://localhost:5000"
\`\`\``;
        }
        return `🎯 **Perfect Solution:**

Your solution involves:
1. Analyze the problem structure
2. Apply best practices
3. Test thoroughly

**Code Example:**
\`\`\`javascript
// Ready-to-use solution code here
console.log('Problem solved!');
\`\`\``;
    }
}

// Initialize when DOM loads
document.addEventListener('DOMContentLoaded', () => {
    new ProAI();
});
